name: Python SDK

on:
  push:
    branches:
      - dev
    paths:
      - "ceramic-client/**"
  workflow_dispatch:
jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: python -m build sdk/python

      - name: Publish package to PyPI
        working-directory: ceramic-client
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*